In [1]:
import pandas as pd
import numpy as np
import talib
from math import atan

# 设定股票池

In [2]:
stocks = get_index_stocks('000300.XSHG',date='2023-01-01')
stocks2 = get_index_stocks('000300.XSHG')
stocks3 = list(set(stocks)&set(stocks2))

In [3]:
# 辅助函数
#计算近N日递增天数
def count_diff(df,n):
    
    diff = df.diff()
    diff[diff > 0] = 1
    diff[diff <= 0] = 0
    count = diff.rolling(window=n).sum()
    
    return count

In [39]:
# 计算因子函数
def process_(df):
    data  = df.copy()
    data['ma5'] = talib.MA(data['close'],timeperiod=5)
    data['ma10'] = talib.MA(data['close'],timeperiod=10)
    data['ma21'] = talib.MA(data['close'],timeperiod=21)
    data['ma55'] = talib.MA(data['close'],timeperiod=55)
    data['vol21'] = talib.MA(data['volume'],timeperiod=21)
    
    data['target2'] = data['close'].shift(-2)/data['close']  # 标签
    
    # 防止分母为零，所以加个无穷小 最后用反三角函数处理将0到无穷大 映射到0到二分之pi 
    data['factor0'] = data.apply(lambda x: atan((x['high']-x['close'])/(x['close']-x['low']+0.00000001)),axis=1)
    data['factor1'] = data.apply(lambda x: atan((x['high']-x['open'])/(x['close']-x['low']+0.00000001)),axis=1)
    data['factor2'] = data.apply(lambda x: atan((x['open']-x['low'])/(x['high']-x['close']+0.00000001)),axis=1)
    data['factor3'] = data.apply(lambda x: atan((x['close']-x['low'])/(x['high']-x['close']+0.00000001)),axis=1)
    
    data['increase5'] = count_diff(df['close'],5) # 近5日价格递增的天数
    data['increase_vol5'] = count_diff(df['volume'],5)
    
    data['return1'] = (data['close']/data['close'].shift(1)-1)*100
    data['return3'] = (data['close']/data['close'].shift(3)-1)*100
    data['return5'] = (data['close']/data['close'].shift(5)-1)*100 #5日涨幅
    
    data['bias5'] = (data['close']/data['ma5']-1)*100 #乖离率
    data['bias10'] = (data['close']/data['ma10']-1)*100
    data['bias21'] = (data['close']/data['ma21']-1)*100
    data['bias55'] = (data['close']/data['ma55']-1)*100
   
    data['bias5_'] = data['bias5']-data['bias5'].shift(1)#乖离率的1阶差分
    data['bias10_'] = data['bias10']-data['bias10'].shift(1)
    data['bias21_'] = data['bias21']-data['bias21'].shift(1)
    data['bias55_'] = data['bias55']-data['bias55'].shift(1)
    
    data['trend5'] = (data['ma5']/data['ma5'].shift(3)-1)*100 # ma5的3日变化率
    data['trend21'] = (data['ma21']/data['ma21'].shift(5)-1)*100 # ma21的5日变化率
    data['high5'] = (data['high']/data['ma5']-1)*100
    data['high10'] = (data['high']/data['ma10']-1)*100
    data['high21'] = (data['high']/data['ma21']-1)*100
    
    data['k1'] = (data['close']-data['open'])/data['close'].shift(1)*2.5 #当日阳线或阴线的长度
    data['k1_1'] = data['k1'].shift(1)
    data['k1_2'] = data['k1'].shift(2)
    data['hc'] = (data['high']/data['close']-1)*100
    data['return1_'] = data['return1']-data['return1'].shift(1)#收益率的一阶差分
    data['return3_'] = data['return3']-data['return3'].shift(1)
    data['return5_'] = data['return5']-data['return5'].shift(1)
    
    data['vol21_'] = (data['volume']/data['vol21']) 
    data['vol21_1'] = data['vol21_']-data['vol21_'].shift(1)
    data['vol21_2'] = data['vol21_']-data['vol21_'].shift(2)
    data['vol21_3'] = data['vol21_']-data['vol21_'].shift(3)
    
    return data.dropna()

# 合并20年-22年 训练数据

In [5]:
target_col = [ 'target2','factor0','factor1','factor2','factor3','return1', 'return3', 'return5', 'bias5', 'bias10', 'bias21', 'bias55',
        'bias5_', 'bias10_', 'bias21_', 'bias55_', 'trend5','increase5','increase_vol5',
       'trend21', 'high5', 'high10', 'high21', 'k1', 'k1_1', 'k1_2', 'hc',
       'return1_', 'return3_', 'return5_','vol21_', 'vol21_1', 'vol21_2',
       'vol21_3']

In [6]:
df = get_price(stocks3[0],'2020-01-01', '2023-01-01','1d')
train = process_(df)[target_col]  #计算因子

for x in stocks3[1:]:
    df = get_price(x,'2020-01-01', '2023-01-01','1d')
    df2= process_(df)[target_col]
    train = pd.concat([train,df2],axis=0) #拼接数据

In [7]:
# 因子范围
train.describe().T

                  count      mean     ...           75%         max
target2        189127.0  1.001788     ...      1.020250    1.427299
factor0        189127.0  0.816961     ...      1.293289    1.570796
factor1        189127.0  0.782773     ...      1.051650    1.570796
factor2        189127.0  0.740043     ...      0.982793    1.570796
factor3        189127.0  0.751377     ...      1.227772    1.570796
return1        189127.0  0.088289     ...      1.320427   20.010935
return3        189127.0  0.270000     ...      2.561327   43.753983
return5        189127.0  0.452668     ...      3.430365  322.171946
bias5          189127.0  0.116083     ...      1.573501   26.927406
bias10         189127.0  0.271499     ...      2.541037   91.080846
bias21         189127.0  0.588450     ...      4.033341  167.892668
bias55         189127.0  1.462341     ...      6.864707  246.074084
bias5_         189127.0 -0.001116     ...      1.267084   18.216291
bias10_        189127.0 -0.000523     ...      1.291756   19.170041
bias21_        189127.0  0.004487     ...      1.290949   21.940972
bias55_        189127.0  0.008238     ...      1.282421   29.308800
trend5         189127.0  0.210278     ...      1.852626  112.054448
increase5      189127.0  2.371528     ...      3.000000    5.000000
increase_vol5  189127.0  2.324972     ...      3.000000    5.000000
trend21        189127.0  0.255903     ...      1.791979   71.493213
high5          189127.0  2.009804     ...      3.311268   30.671919
high10         189127.0  2.170933     ...      4.373360  100.296964
high21         189127.0  2.502517     ...      5.994032  180.813536
k1             189127.0  0.002889     ...      0.032411    0.522311
k1_1           189127.0  0.002897     ...      0.032444    0.522311
k1_2           189127.0  0.002884     ...      0.032442    0.522311
hc             189127.0  1.911040     ...      2.595420   33.209539
return1_       189127.0  0.000156     ...      2.087204   29.848118
return3_       189127.0 -0.005969     ...      2.046929   35.713759
return5_       189127.0 -0.002172     ...      2.092617   27.579152
vol21_         189127.0  1.007145     ...      1.178913    8.621937
vol21_1        189127.0  0.000083     ...      0.195675    8.621937
vol21_2        189127.0 -0.000207     ...      0.238545    8.621937
vol21_3        189127.0 -0.000567     ...      0.263280    8.621937

[34 rows x 8 columns]

In [8]:
# 选择分布在0.1%到99.8%的数据 
df2 = train[(train<=train.quantile(q=0.999)).all(axis=1)]
df2 = df2[(df2>= train.quantile(q=0.001)).all(axis=1)]

# 保存因子边界
train.quantile(q=0.999).to_csv('top.csv',header=None)
train.quantile(q=0.001).to_csv('bottom.csv',header=None)

In [9]:
df2.describe().T

                  count      mean    ...           75%        max
target2        184333.0  1.001644    ...      1.019852   1.209237
factor0        184333.0  0.817771    ...      1.292497   1.570796
factor1        184333.0  0.782314    ...      1.051650   1.570796
factor2        184333.0  0.738985    ...      0.982793   1.570796
factor3        184333.0  0.750920    ...      1.222908   1.570796
return1        184333.0  0.078156    ...      1.286449  11.233752
return3        184333.0  0.227349    ...      2.478667  25.338094
return5        184333.0  0.373782    ...      3.303303  33.135392
bias5          184333.0  0.095818    ...      1.527082  14.891519
bias10         184333.0  0.218225    ...      2.451168  23.796880
bias21         184333.0  0.473573    ...      3.886759  38.557703
bias55         184333.0  1.190651    ...      6.596915  70.524838
bias5_         184333.0  0.004048    ...      1.237049  10.110530
bias10_        184333.0  0.004948    ...      1.261133  10.389558
bias21_        184333.0  0.007970    ...      1.261032  10.705562
bias55_        184333.0  0.011098    ...      1.253440  12.777905
trend5         184333.0  0.168665    ...      1.790073  17.301782
increase5      184333.0  2.365713    ...      3.000000   5.000000
increase_vol5  184333.0  2.318125    ...      3.000000   5.000000
trend21        184333.0  0.207739    ...      1.735917  14.682928
high5          184333.0  1.941166    ...      3.233150  17.681708
high10         184333.0  2.067801    ...      4.246237  27.404685
high21         184333.0  2.334581    ...      5.811226  43.111469
k1             184333.0  0.002655    ...      0.031712   0.292832
k1_1           184333.0  0.002587    ...      0.031726   0.292832
k1_2           184333.0  0.002561    ...      0.031742   0.292832
hc             184333.0  1.860203    ...      2.551950  12.567050
return1_       184333.0  0.003666    ...      2.040802  15.758089
return3_       184333.0  0.002397    ...      2.007238  16.786072
return5_       184333.0  0.001466    ...      2.053638  16.576474
vol21_         184333.0  0.989913    ...      1.164548   4.526372
vol21_1        184333.0 -0.002285    ...      0.192023   2.819909
vol21_2        184333.0 -0.004360    ...      0.232742   3.261187
vol21_3        184333.0 -0.007579    ...      0.255696   3.363700

[34 rows x 8 columns]

# 随机森林

In [10]:
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df2.drop(columns='target2'), df2['target2'], test_size=0.1, random_state=36)

In [12]:
X_train.head()

             factor0   factor1   factor2    ...      vol21_1   vol21_2   vol21_3
2021-11-19  0.262995  0.839890  0.519146    ...    -1.159363 -0.084381  0.136937
2021-08-12  0.785398  0.000000  1.107148    ...    -0.423877 -0.389300 -0.527417
2020-07-20  0.165149  0.785398  0.785398    ...     0.120976 -0.359655 -0.258409
2021-01-27  0.812419  0.923274  0.607185    ...    -0.486860 -0.676765 -0.479239
2021-03-11  1.249046  0.605545  0.834140    ...     1.764308  1.726317  1.404366

[5 rows x 33 columns]

In [13]:
model = RandomForestRegressor(n_estimators=100,max_depth=7, random_state=0)
model.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=7,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [14]:
from sklearn.metrics import r2_score, mean_squared_error

In [15]:
# 测试并计算 R2 分数以及均方误差
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print('R2 score:', r2)
print('Mean Squared Error:', mse)

R2 score: 0.008128496811839914
Mean Squared Error: 0.001480745773393013

In [16]:
import joblib

# 保存模型 
joblib.dump(model, 'model.joblib')

['model.joblib']

# 预测

预测23年以后的选股并排序

In [18]:
target_col = ['factor0','factor1','factor2','factor3','return1', 'return3', 'return5', 'bias5', 'bias10', 'bias21', 'bias55',
        'bias5_', 'bias10_', 'bias21_', 'bias55_', 'trend5','increase5','increase_vol5',
       'trend21', 'high5', 'high10', 'high21', 'k1', 'k1_1', 'k1_2', 'hc',
       'return1_', 'return3_', 'return5_','vol21_', 'vol21_1', 'vol21_2',
       'vol21_3']

In [19]:
top = pd.read_csv('top.csv',header=None,index_col=0,squeeze=True)
top = top.drop('target2')
bottom = pd.read_csv('bottom.csv',header=None,index_col=0,squeeze=True)
bottom = bottom.drop('target2')

In [29]:
# 获取预测 因子计算要用历史数据 getprice 多往前取一些
def get_predict(model,name):
    ddf = get_price(name,'2022-05-01', end_date='2023-06-21',frequency='1d')
    factor = process_(ddf) #计算因子

    factor2 = factor[target_col][(factor[target_col]<=top).all(axis=1)]
    factor2 = factor2[(factor2>=bottom).all(axis=1)] 
#     print(factor)
    tar = model.predict(factor2)
    testdf = pd.DataFrame(tar,index=factor2.index,columns=[name])
        
    return testdf,factor['target2']

In [42]:
pre_df, tar_df = get_predict(model,stocks3[0])

for x in stocks3[1:]:
    pre_df2, tar_df2 = get_predict(model,x)
    tar_df2.name = x
    pre_df = pd.concat([pre_df,pre_df2],join='outer',axis=1)
    tar_df = pd.concat([tar_df,tar_df2],join='outer',axis=1)

In [43]:
# 预测值
pre_df.head()

            601088.XSHG  000895.XSHE     ...       601857.XSHG  601658.XSHG
2022-07-22     1.000432     1.000492     ...          1.000123     1.000139
2022-07-25     1.001684     1.000161     ...          1.000123     1.000000
2022-07-26     1.000281     1.000161     ...          1.000139     1.000202
2022-07-27     1.000165     1.000161     ...          1.000123     1.000123
2022-07-28     1.000123     1.000161     ...          1.000139     1.000123

[5 rows x 291 columns]

In [44]:
# 保存预测结果
# 在回测中可以任意选topK买入
pre_df.to_csv('predict.csv')
tar_df.to_csv('target.csv')

### 第一种选股方法
根据预测值排序选股

In [45]:
dff = pd.read_csv("predict.csv",index_col=0)
dff2 = pd.read_csv("target.csv",index_col=0)

In [46]:
dff.head()

            601088.XSHG  000895.XSHE     ...       601857.XSHG  601658.XSHG
2022-07-22     1.000432     1.000492     ...          1.000123     1.000139
2022-07-25     1.001684     1.000161     ...          1.000123     1.000000
2022-07-26     1.000281     1.000161     ...          1.000139     1.000202
2022-07-27     1.000165     1.000161     ...          1.000123     1.000123
2022-07-28     1.000123     1.000161     ...          1.000139     1.000123

[5 rows x 291 columns]

In [47]:
indexlist = dff['2023':].index.tolist()
dict_position = {}

for x in indexlist:
    # 排序选股
    temp = dff.loc[x].sort_values(ascending=False).head(3).index.tolist()
    
    dict_position[x] = temp

In [48]:
dict_position

{'2023-01-03': ['600050.XSHG', '002252.XSHE', '300413.XSHE'],
 '2023-01-04': ['000938.XSHE', '601155.XSHG', '300769.XSHE'],
 '2023-01-05': ['002241.XSHE', '002920.XSHE', '300896.XSHE'],
 '2023-01-06': ['603806.XSHG', '000301.XSHE', '601877.XSHG'],
 '2023-01-09': ['601877.XSHG', '601899.XSHG', '002304.XSHE'],
 '2023-01-10': ['000425.XSHE', '600085.XSHG', '688599.XSHG'],
 '2023-01-11': ['002252.XSHE', '688599.XSHG', '000938.XSHE'],
 '2023-01-12': ['688005.XSHG', '002493.XSHE', '300919.XSHE'],
 '2023-01-13': ['603486.XSHG', '002311.XSHE', '601066.XSHG'],
 '2023-01-16': ['002821.XSHE', '600276.XSHG', '603486.XSHG'],
 '2023-01-17': ['605117.XSHG', '300769.XSHE', '300122.XSHE'],
 '2023-01-18': ['002555.XSHE', '002821.XSHE', '300759.XSHE'],
 '2023-01-19': ['300759.XSHE', '002230.XSHE', '002180.XSHE'],
 '2023-01-20': ['600050.XSHG', '603369.XSHG', '600845.XSHG'],
 '2023-01-30': ['601689.XSHG', '002230.XSHE', '300896.XSHE'],
 '2023-01-31': ['002120.XSHE', '300759.XSHE', '688008.XSHG'],
 '2023-02-01': ['601236.XSHG', '300759.XSHE', '688008.XSHG'],
 '2023-02-02': ['300759.XSHE', '300454.XSHE', '688111.XSHG'],
 '2023-02-03': ['002241.XSHE', '002064.XSHE', '300347.XSHE'],
 '2023-02-06': ['002648.XSHE', '002601.XSHE', '688111.XSHG'],
 '2023-02-07': ['002050.XSHE', '603185.XSHG', '601360.XSHG'],
 '2023-02-08': ['000977.XSHE', '002460.XSHE', '603019.XSHG'],
 '2023-02-09': ['000977.XSHE', '605499.XSHG', '603019.XSHG'],
 '2023-02-10': ['300033.XSHE', '603486.XSHG', '603369.XSHG'],
 '2023-02-13': ['688561.XSHG', '600183.XSHG', '688111.XSHG'],
 '2023-02-14': ['000425.XSHE', '603019.XSHG', '002050.XSHE'],
 '2023-02-15': ['002841.XSHE', '603993.XSHG', '300751.XSHE'],
 '2023-02-16': ['300751.XSHE', '002120.XSHE', '601799.XSHG'],
 '2023-02-17': ['002120.XSHE', '600233.XSHG', '000100.XSHE'],
 '2023-02-20': ['601728.XSHG', '000425.XSHE', '000938.XSHE'],
 '2023-02-21': ['000425.XSHE', '600019.XSHG', '000651.XSHE'],
 '2023-02-22': ['002714.XSHE', '600309.XSHG', '688561.XSHG'],
 '2023-02-23': ['601728.XSHG', '601360.XSHG', '603019.XSHG'],
 '2023-02-24': ['603019.XSHG', '002841.XSHE', '601633.XSHG'],
 '2023-02-27': ['000977.XSHE', '603019.XSHG', '002230.XSHE'],
 '2023-02-28': ['002241.XSHE', '601728.XSHG', '600050.XSHG'],
 '2023-03-01': ['600050.XSHG', '600588.XSHG', '601360.XSHG'],
 '2023-03-02': ['601618.XSHG', '601868.XSHG', '601138.XSHG'],
 '2023-03-03': ['601138.XSHG', '601117.XSHG', '601766.XSHG'],
 '2023-03-06': ['002129.XSHE', '688396.XSHG', '300316.XSHE'],
 '2023-03-07': ['603486.XSHG', '603195.XSHG', '601360.XSHG'],
 '2023-03-08': ['000977.XSHE', '601728.XSHG', '002129.XSHE'],
 '2023-03-09': ['000938.XSHE', '601138.XSHG', '600028.XSHG'],
 '2023-03-10': ['601689.XSHG', '300957.XSHE', '603019.XSHG'],
 '2023-03-13': ['600941.XSHG', '600588.XSHG', '000977.XSHE'],
 '2023-03-14': ['000876.XSHE', '000625.XSHE', '601117.XSHG'],
 '2023-03-15': ['000977.XSHE', '000425.XSHE', '002920.XSHE'],
 '2023-03-16': ['601360.XSHG', '300274.XSHE', '688561.XSHG'],
 '2023-03-17': ['605117.XSHG', '300274.XSHE', '002236.XSHE'],
 '2023-03-20': ['605117.XSHG', '300274.XSHE', '002459.XSHE'],
 '2023-03-21': ['688561.XSHG', '603259.XSHG', '002756.XSHE'],
 '2023-03-22': ['605117.XSHG', '600588.XSHG', '601390.XSHG'],
 '2023-03-23': ['000977.XSHE', '688111.XSHG', '603986.XSHG'],
 '2023-03-24': ['002475.XSHE', '603986.XSHG', '002049.XSHE'],
 '2023-03-27': ['002410.XSHE', '600188.XSHG', '601698.XSHG'],
 '2023-03-28': ['002493.XSHE', '300628.XSHE', '601117.XSHG'],
 '2023-03-29': ['002371.XSHE', '688036.XSHG', '000977.XSHE'],
 '2023-03-30': ['603986.XSHG', '601698.XSHG', '601360.XSHG'],
 '2023-03-31': ['002236.XSHE', '600570.XSHG', '000977.XSHE'],
 '2023-04-03': ['000938.XSHE', '300347.XSHE', '601688.XSHG'],
 '2023-04-04': ['601390.XSHG', '300759.XSHE', '601186.XSHG'],
 '2023-04-06': ['600460.XSHG', '300919.XSHE', '600547.XSHG'],
 '2023-04-07': ['600570.XSHG', '002493.XSHE', '001979.XSHE'],
 '2023-04-10': ['000938.XSHE', '300454.XSHE', '600460.XSHG'],
 '2023-04-11': ['600745.XSHG', '688111.XSHG', '002230.XSHE'],
 '2023-04-12': ['600570.XSHG', '002555.XSHE', '002230.XSHE'],
 '2023-04-13': ['688111.XSHG', '300033.XSHE', '688036.XSHG'],
 '2023-04-14': ['002756.XSHE', '688111.XSHG', '300033.XSHE'],
 '2023-04-17': ['300628.XSHE', '601360.XSHG', '000800.XSHE'],
 '2023-04-18': ['600089.XSHG', '600919.XSHG', '000977.XSHE'],
 '2023-04-19': ['688012.XSHG', '300413.XSHE', '688981.XSHG'],
 '2023-04-20': ['002938.XSHE', '688036.XSHG', '002230.XSHE'],
 '2023-04-21': ['601689.XSHG', '002415.XSHE', '002493.XSHE'],
 '2023-04-24': ['300496.XSHE', '300782.XSHE', '002241.XSHE'],
 '2023-04-25': ['300496.XSHE', '300782.XSHE', '300033.XSHE'],
 '2023-04-26': ['603799.XSHG', '300782.XSHE', '603185.XSHG'],
 '2023-04-27': ['601698.XSHG', '688561.XSHG', '002236.XSHE'],
 '2023-04-28': ['688111.XSHG', '688126.XSHG', '603019.XSHG'],
 '2023-05-04': ['002555.XSHE', '002027.XSHE', '688303.XSHG'],
 '2023-05-05': ['601138.XSHG', '002938.XSHE', '300223.XSHE'],
 '2023-05-08': ['600436.XSHG', '600150.XSHG', '601988.XSHG'],
 '2023-05-09': ['601995.XSHG', '002371.XSHE', '002938.XSHE'],
 '2023-05-10': ['002555.XSHE', '605117.XSHG', '002920.XSHE'],
 '2023-05-11': ['601881.XSHG', '000977.XSHE', '605117.XSHG'],
 '2023-05-12': ['002049.XSHE', '601899.XSHG', '603019.XSHG'],
 '2023-05-15': ['600150.XSHG', '002459.XSHE', '002466.XSHE'],
 '2023-05-16': ['300413.XSHE', '601881.XSHG', '601698.XSHG'],
 '2023-05-17': ['603019.XSHG', '688036.XSHG', '601728.XSHG'],
 '2023-05-18': ['300033.XSHE', '002230.XSHE', '603019.XSHG'],
 '2023-05-19': ['600150.XSHG', '688036.XSHG', '601989.XSHG'],
 '2023-05-22': ['001289.XSHE', '600809.XSHG', '000568.XSHE'],
 '2023-05-23': ['300033.XSHE', '601360.XSHG', '601319.XSHG'],
 '2023-05-24': ['300033.XSHE', '601628.XSHG', '601601.XSHG'],
 '2023-05-25': ['601138.XSHG', '300033.XSHE', '000938.XSHE'],
 '2023-05-26': ['600332.XSHG', '601633.XSHG', '601225.XSHG'],
 '2023-05-29': ['300496.XSHE', '601633.XSHG', '601012.XSHG'],
 '2023-05-30': ['000977.XSHE', '601012.XSHG', '603806.XSHG'],
 '2023-05-31': ['603806.XSHG', '600188.XSHG', '002459.XSHE'],
 '2023-06-01': ['002230.XSHE', '300782.XSHE', '600029.XSHG'],
 '2023-06-02': ['600188.XSHG', '601689.XSHG', '002271.XSHE'],
 '2023-06-05': ['688599.XSHG', '002371.XSHE', '601138.XSHG'],
 '2023-06-06': ['601669.XSHG', '300347.XSHE', '688599.XSHG'],
 '2023-06-07': ['300347.XSHE', '603392.XSHG', '688599.XSHG'],
 '2023-06-08': ['300751.XSHE', '688599.XSHG', '300769.XSHE'],
 '2023-06-09': ['603392.XSHG', '601138.XSHG', '002555.XSHE'],
 '2023-06-12': ['002920.XSHE', '002050.XSHE', '002415.XSHE'],
 '2023-06-13': ['002415.XSHE', '002050.XSHE', '603986.XSHG'],
 '2023-06-14': ['300769.XSHE', '002920.XSHE', '688005.XSHG'],
 '2023-06-15': ['600845.XSHG', '300014.XSHE', '300769.XSHE'],
 '2023-06-16': ['002236.XSHE', '688111.XSHG', '002074.XSHE'],
 '2023-06-19': ['600183.XSHG', '002236.XSHE', '002648.XSHE']}

### 第二种选股方法

根据模型在近十日中个股的误差和预测值进行排序

_这个方法可能效果不好_

In [49]:
mae_df = dff-dff2
mae_df = mae_df.abs().rolling(10).mean()
mae_df.head()

            000001.XSHE  000002.XSHE   ...     688981.XSHG  target2
2022-07-22          NaN          NaN   ...             NaN      NaN
2022-07-25          NaN          NaN   ...             NaN      NaN
2022-07-26          NaN          NaN   ...             NaN      NaN
2022-07-27          NaN          NaN   ...             NaN      NaN
2022-07-28          NaN          NaN   ...             NaN      NaN

[5 rows x 292 columns]

In [50]:
# 因为我们的标签使用的是2日后的收盘价，所以评估效果的数据进行下移两个位置的操作 防止使用未来信息
mae_df = mae_df.shift(2)['2023':]
mae_df.head()

            000001.XSHE  000002.XSHE   ...     688981.XSHG  target2
2023-01-03     0.019217     0.017068   ...        0.013304      NaN
2023-01-04     0.023614     0.018097   ...        0.012445      NaN
2023-01-05     0.027077     0.020340   ...        0.011853      NaN
2023-01-06     0.027883     0.020718   ...        0.010553      NaN
2023-01-09     0.029384     0.023226   ...        0.010791      NaN

[5 rows x 292 columns]

In [51]:
indexlist = dff['2023':].index.tolist()
dict_position2 = {}

for x in indexlist:
    # 排序选股
    temp = pd.concat([dff.loc[x],-mae_df.loc[x]],axis=1,keys=['s1', 's2']).dropna()
    
    dict_position2[x] = temp.sort_values(by=['s1', 's2'],ascending=False).head(3).index.tolist()
    
    
dict_position2

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

{'2023-01-03': ['600050.XSHG', '002252.XSHE', '300413.XSHE'],
 '2023-01-04': ['000938.XSHE', '601155.XSHG', '300769.XSHE'],
 '2023-01-05': ['002241.XSHE', '002920.XSHE', '300896.XSHE'],
 '2023-01-06': ['603806.XSHG', '000301.XSHE', '601877.XSHG'],
 '2023-01-09': ['601877.XSHG', '601899.XSHG', '002304.XSHE'],
 '2023-01-10': ['000425.XSHE', '600085.XSHG', '688599.XSHG'],
 '2023-01-11': ['002252.XSHE', '688599.XSHG', '603806.XSHG'],
 '2023-01-12': ['688005.XSHG', '002493.XSHE', '300919.XSHE'],
 '2023-01-13': ['603486.XSHG', '002311.XSHE', '601066.XSHG'],
 '2023-01-16': ['002821.XSHE', '600276.XSHG', '603486.XSHG'],
 '2023-01-17': ['605117.XSHG', '300769.XSHE', '300122.XSHE'],
 '2023-01-18': ['002555.XSHE', '002821.XSHE', '300759.XSHE'],
 '2023-01-19': ['300759.XSHE', '002230.XSHE', '002180.XSHE'],
 '2023-01-20': ['600050.XSHG', '603369.XSHG', '603486.XSHG'],
 '2023-01-30': ['601689.XSHG', '002230.XSHE', '002812.XSHE'],
 '2023-01-31': ['002120.XSHE', '300759.XSHE', '688008.XSHG'],
 '2023-02-01': ['601236.XSHG', '300759.XSHE', '688008.XSHG'],
 '2023-02-02': ['300759.XSHE', '688111.XSHG', '002230.XSHE'],
 '2023-02-03': ['002241.XSHE', '002064.XSHE', '300347.XSHE'],
 '2023-02-06': ['002648.XSHE', '688111.XSHG', '300601.XSHE'],
 '2023-02-07': ['002050.XSHE', '603185.XSHG', '601360.XSHG'],
 '2023-02-08': ['000977.XSHE', '002460.XSHE', '603019.XSHG'],
 '2023-02-09': ['000977.XSHE', '605499.XSHG', '603019.XSHG'],
 '2023-02-10': ['300033.XSHE', '603486.XSHG', '603369.XSHG'],
 '2023-02-13': ['688561.XSHG', '600183.XSHG', '603899.XSHG'],
 '2023-02-14': ['000425.XSHE', '603019.XSHG', '002050.XSHE'],
 '2023-02-15': ['002841.XSHE', '603993.XSHG', '300751.XSHE'],
 '2023-02-16': ['300751.XSHE', '002120.XSHE', '601799.XSHG'],
 '2023-02-17': ['002120.XSHE', '600233.XSHG', '603019.XSHG'],
 '2023-02-20': ['601728.XSHG', '000938.XSHE', '000063.XSHE'],
 '2023-02-21': ['600019.XSHG', '000651.XSHE', '601995.XSHG'],
 '2023-02-22': ['002714.XSHE', '600309.XSHG', '688561.XSHG'],
 '2023-02-23': ['601728.XSHG', '603019.XSHG', '000063.XSHE'],
 '2023-02-24': ['603019.XSHG', '002841.XSHE', '601633.XSHG'],
 '2023-02-27': ['603019.XSHG', '002230.XSHE', '002236.XSHE'],
 '2023-02-28': ['002241.XSHE', '601728.XSHG', '600050.XSHG'],
 '2023-03-01': ['600050.XSHG', '600588.XSHG', '002236.XSHE'],
 '2023-03-02': ['601618.XSHG', '601868.XSHG', '601138.XSHG'],
 '2023-03-03': ['601138.XSHG', '601117.XSHG', '601766.XSHG'],
 '2023-03-06': ['002129.XSHE', '688396.XSHG', '300316.XSHE'],
 '2023-03-07': ['603486.XSHG', '603195.XSHG', '601186.XSHG'],
 '2023-03-08': ['002129.XSHE', '603486.XSHG', '000786.XSHE'],
 '2023-03-09': ['000938.XSHE', '600028.XSHG', '600150.XSHG'],
 '2023-03-10': ['601689.XSHG', '300957.XSHE', '603019.XSHG'],
 '2023-03-13': ['600941.XSHG', '600588.XSHG', '300957.XSHE'],
 '2023-03-14': ['000876.XSHE', '000625.XSHE', '002920.XSHE'],
 '2023-03-15': ['000425.XSHE', '002920.XSHE', '300014.XSHE'],
 '2023-03-16': ['601360.XSHG', '300274.XSHE', '688561.XSHG'],
 '2023-03-17': ['605117.XSHG', '300274.XSHE', '002236.XSHE'],
 '2023-03-20': ['300274.XSHE', '002459.XSHE', '300014.XSHE'],
 '2023-03-21': ['603259.XSHG', '002756.XSHE', '603899.XSHG'],
 '2023-03-22': ['601390.XSHG', '603019.XSHG', '002371.XSHE'],
 '2023-03-23': ['603986.XSHG', '002230.XSHE', '002049.XSHE'],
 '2023-03-24': ['002475.XSHE', '603986.XSHG', '002049.XSHE'],
 '2023-03-27': ['002410.XSHE', '600188.XSHG', '300413.XSHE'],
 '2023-03-28': ['002493.XSHE', '601117.XSHG', '688008.XSHG'],
 '2023-03-29': ['002371.XSHE', '000977.XSHE', '688008.XSHG'],
 '2023-03-30': ['603986.XSHG', '300223.XSHE', '601236.XSHG'],
 '2023-03-31': ['002236.XSHE', '300347.XSHE', '000063.XSHE'],
 '2023-04-03': ['000938.XSHE', '300347.XSHE', '601688.XSHG'],
 '2023-04-04': ['601390.XSHG', '601186.XSHG', '601800.XSHG'],
 '2023-04-06': ['600460.XSHG', '300919.XSHE', '600547.XSHG'],
 '2023-04-07': ['001979.XSHE', '300347.XSHE', '688126.XSHG'],
 '2023-04-10': ['000938.XSHE', '300454.XSHE', '600460.XSHG'],
 '2023-04-11': ['600745.XSHG', '002230.XSHE', '002555.XSHE'],
 '2023-04-12': ['000938.XSHE', '603369.XSHG', '601698.XSHG'],
 '2023-04-13': ['603369.XSHG', '603806.XSHG', '300628.XSHE'],
 '2023-04-14': ['002756.XSHE', '603019.XSHG', '300496.XSHE'],
 '2023-04-17': ['300628.XSHE', '000800.XSHE', '002920.XSHE'],
 '2023-04-18': ['600089.XSHG', '600919.XSHG', '600000.XSHG'],
 '2023-04-19': ['688981.XSHG', '603993.XSHG', '600015.XSHG'],
 '2023-04-20': ['002938.XSHE', '300661.XSHE', '688126.XSHG'],
 '2023-04-21': ['601689.XSHG', '002415.XSHE', '002493.XSHE'],
 '2023-04-24': ['300496.XSHE', '300782.XSHE', '688363.XSHG'],
 '2023-04-25': ['300496.XSHE', '300782.XSHE', '603260.XSHG'],
 '2023-04-26': ['603799.XSHG', '300782.XSHE', '603185.XSHG'],
 '2023-04-27': ['688561.XSHG', '002236.XSHE', '603259.XSHG'],
 '2023-04-28': ['688126.XSHG', '000938.XSHE', '688561.XSHG'],
 '2023-05-04': ['002555.XSHE', '002027.XSHE', '688303.XSHG'],
 '2023-05-05': ['002938.XSHE', '300223.XSHE', '603986.XSHG'],
 '2023-05-08': ['600436.XSHG', '600150.XSHG', '601988.XSHG'],
 '2023-05-09': ['601995.XSHG', '002371.XSHE', '002938.XSHE'],
 '2023-05-10': ['002920.XSHE', '000625.XSHE', '002756.XSHE'],
 '2023-05-11': ['000977.XSHE', '300413.XSHE', '601988.XSHG'],
 '2023-05-12': ['002049.XSHE', '601899.XSHG', '688126.XSHG'],
 '2023-05-15': ['600150.XSHG', '002459.XSHE', '002466.XSHE'],
 '2023-05-16': ['300413.XSHE', '601186.XSHG', '600011.XSHG'],
 '2023-05-17': ['601728.XSHG', '000977.XSHE', '300413.XSHE'],
 '2023-05-18': ['603019.XSHG', '601689.XSHG', '688111.XSHG'],
 '2023-05-19': ['600150.XSHG', '601989.XSHG', '603019.XSHG'],
 '2023-05-22': ['001289.XSHE', '600809.XSHG', '000568.XSHE'],
 '2023-05-23': ['300033.XSHE', '601360.XSHG', '601319.XSHG'],
 '2023-05-24': ['300033.XSHE', '601628.XSHG', '601601.XSHG'],
 '2023-05-25': ['601138.XSHG', '300033.XSHE', '000938.XSHE'],
 '2023-05-26': ['600332.XSHG', '601633.XSHG', '601225.XSHG'],
 '2023-05-29': ['300496.XSHE', '601633.XSHG', '601012.XSHG'],
 '2023-05-30': ['000977.XSHE', '601012.XSHG', '603806.XSHG'],
 '2023-05-31': ['603806.XSHG', '600188.XSHG', '002459.XSHE'],
 '2023-06-01': ['002230.XSHE', '300782.XSHE', '600029.XSHG'],
 '2023-06-02': ['600188.XSHG', '601689.XSHG', '002271.XSHE'],
 '2023-06-05': ['002371.XSHE', '601138.XSHG', '300751.XSHE'],
 '2023-06-06': ['601669.XSHG', '300347.XSHE', '300223.XSHE'],
 '2023-06-07': ['300347.XSHE', '603392.XSHG', '600584.XSHG'],
 '2023-06-08': ['300751.XSHE', '300769.XSHE', '603806.XSHG'],
 '2023-06-09': ['603392.XSHG', '601138.XSHG', '002555.XSHE'],
 '2023-06-12': ['002920.XSHE', '002050.XSHE', '002415.XSHE'],
 '2023-06-13': ['002415.XSHE', '002050.XSHE', '603986.XSHG'],
 '2023-06-14': ['300769.XSHE', '002920.XSHE', '688005.XSHG'],
 '2023-06-15': ['600845.XSHG', '300014.XSHE', '300769.XSHE'],
 '2023-06-16': ['002236.XSHE', '002074.XSHE', '688036.XSHG'],
 '2023-06-19': ['600183.XSHG', '002236.XSHE', '002648.XSHE']}